spring:
  profiles:
    active: "romania"
    default: "hungary"
  data:
    web:
      pageable:
        default-page-size: 10
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
